<?php
/**
 * Thin PHP wrapper for the contact page.
 * Reads the static HTML generated by Eleventy and injects form messages
 * based on query parameters (set by the API redirect).
 */

$messages = [
    'contact_success' => ['type' => 'success', 'text' => 'Dziękujemy! Twoja wiadomość została wysłana.'],
    'contact_error'   => ['type' => 'error',   'text' => 'Wystąpił błąd. Spróbuj ponownie później.'],
    'bot_error'       => ['type' => 'error',   'text' => 'Sorry, ale wygląda na to, że nie jesteś człowiekiem.'],
];

// Read the static HTML (contact/index.html in the same deployment directory)
$html = file_get_contents(__DIR__ . '/index.html');

if ($html === false) {
    http_response_code(500);
    exit('Error: Could not load page.');
}

// Inject message if present
$msg = $_GET['msg'] ?? '';
if ($msg && isset($messages[$msg])) {
    $messageData = $messages[$msg];
    $messageHtml = '<div class="form-message form-message-' . htmlspecialchars($messageData['type']) . '">'
        . '<span class="material-symbols-outlined">'
        . ($messageData['type'] === 'success' ? 'check_circle' : 'error')
        . '</span>'
        . '<span>' . htmlspecialchars($messageData['text']) . '</span>'
        . '</div>';

    // Replace the placeholder comment with the actual message
    $html = str_replace('<!-- form-message-placeholder -->', $messageHtml, $html);
}

echo $html;
