<?php
/**
 * Thin PHP wrapper for the home page.
 * Reads the static HTML generated by Eleventy and injects form messages
 * based on query parameters (set by the API redirect).
 */

$messages = [
    'subscribe_success' => ['type' => 'success', 'text' => 'Dziękujemy! Sprawdź swoją skrzynkę email i kliknij link weryfikacyjny.'],
    'subscribe_error'   => ['type' => 'error',   'text' => 'Wystąpił błąd. Spróbuj ponownie później.'],
    'subscribe_info'    => ['type' => 'info',    'text' => 'Ten adres email jest już zapisany na naszej liście.'],
    'verify_success'    => ['type' => 'success', 'text' => 'Dziękujemy! Twój adres email został zweryfikowany. Będziesz otrzymywać aktualizacje o projekcie WikiZEIT.'],
    'verify_error'      => ['type' => 'error',   'text' => 'Nieprawidłowy lub wygasły link weryfikacyjny.'],
    'verify_info'       => ['type' => 'info',    'text' => 'Ten adres email został już wcześniej zweryfikowany.'],
    'bot_error'         => ['type' => 'error',   'text' => 'Sorry, ale wygląda na to, że nie jesteś człowiekiem.'],
];

// Read the static HTML (same directory after deployment)
$html = file_get_contents(__DIR__ . '/index.html');

if ($html === false) {
    http_response_code(500);
    exit('Error: Could not load page.');
}

// Inject message if present
$msg = $_GET['msg'] ?? '';
if ($msg && isset($messages[$msg])) {
    $messageData = $messages[$msg];
    $messageHtml = '<div class="form-message form-message-' . htmlspecialchars($messageData['type']) . '">'
        . '<span class="material-symbols-outlined">'
        . ($messageData['type'] === 'success' ? 'check_circle' : ($messageData['type'] === 'error' ? 'error' : 'info'))
        . '</span>'
        . '<span>' . htmlspecialchars($messageData['text']) . '</span>'
        . '</div>';

    // Replace the placeholder comment with the actual message
    $html = str_replace('<!-- form-message-placeholder -->', $messageHtml, $html);
}

echo $html;
